name = "civicenia-shop-counter"
main = "worker.mjs"
compatibility_date = "2026-02-06"

# Replace with your Cloudflare Account ID
account_id = "32d6ad3c4725cacc38c162cc2a3d19cf"

workers_dev = true

[build]
command = ""

[durable_objects]
bindings = [
  { name = "SHOP_COUNTER", class_name = "Counter" }
]

[[migrations]]
tag = "v1"
# For free plan, Durable Objects require a sqlite-backed migration
new_sqlite_classes = ["Counter"]
